# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "quiz-app"
client_id = "33bb8f7b29ea1b92de775cda40c64320"
application_url = "https://helmet-wilderness-basis-control.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://helmet-wilderness-basis-control.trycloudflare.com/auth/callback",
  "https://helmet-wilderness-basis-control.trycloudflare.com/auth/shopify/callback",
  "https://helmet-wilderness-basis-control.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appmixo-disha.myshopify.com"
